#!/bin/sh
### BEGIN INIT INFO
# Provides:		rfidjukebox_rfid_daemon
# Default-Start:	2 3 4 5
# Default-Stop:		1
# Short-Description:	rfidjukebox rfid daemon
### END INIT INFO
#
# Do not configure this file. Edit /etc/default/dropbear instead!
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/pi/RPi-Jukebox-RFID/scripts/daemon_rfid_reader.py
NAME=rfidjukebox_rfid_daemon
DESC="rfidjukebox rfid daemon"
PIDFILE=/var/run/rfidjukebox_rfid_daemon.pid

case "$1" in
  start)
        echo -n "Starting $DESC: "
        start-stop-daemon -S -p $PIDFILE \
          -x "$DAEMON" -b
        echo "$NAME."
        ;;

  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon -K -x "$DAEMON" -p $PIDFILE
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	stop
	sleep 1
	start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
